Makefile, README.md, create/create.go, create/fsutils/fsutils.go, create/process/process.go, create/templates/integration_test/javascript.js, create/templates/integration_test/package.json, create/templates/integration_test/react.js, create/templates/integration_test/shopifile.yml, create/templates/integration_test/src/Country.graphql, create/templates/shopifile.yml.tpl, packages/shopify-cli-extensions/src/configs.ts, testdata/extensions/checkout_ui_extension/build/index.js, testdata/shopifile.integration.yml
1. Run `make bootstrap` and verify that there are no errors
2. Run `make run serve < testdata/shopifile.yml`
3. Visit http://localhost:8000/extensions/00000000-0000-0000-0000-000000000000/assets/main.js and verify that the JS bundle loads
=> Integration test with graphql

.github/workflows/release.yml
Use `gh` to upload assets to a release instead of relying on a thrid party action. This reduce the risk of tokens being abused.
=> Use GH for Asset Handling

.github/workflows/release.yml, .github/workflows/testing.yml, Makefile, main.go
This PR tweaks our release workflow
* Stop wrapping the binaries in tarballs – it's unnecessary because we're compressing a single file and possibly related to the Windows issue I'm investigating
* Produce md5 sum files for verification purposes
* Change version update mechanism from using `sed` to using `ruby`
* Run packaging tests on every PR to ensure that our release workflow isn't broken
=> Use GZip only

api/api.go, api/api_test.go, main.go
Fix https://github.com/Shopify/shopify-cli-extensions/issues/70
Run `make bootstrap; make build` to set up
**Client close connection**
1. Run `./shopify-extensions serve < testdata/shopifile.yml`
2. In a web browser, open a console and paste the following code
```js
var ws = new WebSocket("ws://localhost:8000/extensions/");
ws.onClose = console.log;
ws.close(1000, "done");
```
3. Verify that the console logs out a close event with the code `1000`, the reason set to `"done"` and `wasClean = true`
**Server shut down**
1. Run `./shopify-extensions serve < testdata/shopifile.yml`
2. In a web browser, open a console and paste the following code
```js
var ws = new WebSocket("ws://localhost:8000/extensions/");
ws.onClose = console.log;
```
3. In the terminal running serve, kill the process. Note …
=> Websocket shutdown

api/api.go, api/api_test.go, api/testdata/shopifile.yml, core/core.go
Related to https://github.com/Shopify/shopify-cli-extensions/issues/95
- use a custom transformer with`mergo.Merge` to allow updating extension data after initial values are set and support setting booleans to `false`
- populate extension urls dynamically with every response
1. Run `make bootstrap` and then `make run serve testdata/shopifile.yml`
2. In another terminal, run `ngrok http 8000`
2. Open http://localhost:8000/extensions/ in the browser and open the Chrome console.
3. Connect to the websocket `var notSecure = new WebSocket("ws:localhost:8000/extensions/")`
4. Verify that you receive a "connected" payload with all extension urls starting with `http://localhost:8000`
5. Connect to the secure websocket, ex.`var secure = new WebSocket("wss:d7d8-45-3-5-121.ngrok.io/extensions/")`
6. …
=> Fix extension urls and merging update data

api/api.go, api/api_test.go, api/root/root.go, api/root/templates/checkout_post_purchase/index.html.tpl, api/root/templates/checkout_post_purchase/tunnel-error.html.tpl, api/root/templates/error.html.tpl, api/root/templates/tunnel-error.html.tpl, api/testdata/shopifile.yml, core/core.go, core/fsutils/fsutils.go, create/create.go, testdata/shopifile.yml
- render tunnel error page for post-purchase, checkout and admin extensions when accessed via localhost
- render instructions page for post-purchase extensions when accessed through a tunnel
- redirect to the store's resource url for checkout extensions when accessed through a tunnel
- redirect to the store's admin extensions-dev for admin extensions when accessed through a tunnel
Fix https://github.com/Shopify/shopify-cli-extensions/issues/53
1. Run `make bootstrap`
2. Run `make run serve testdata/shopifile.yml`
3. In another terminal, run `ngrok http 8000` and make a note of your tunnel url
**Checkout**
1. Navigate to http://localhost:8000/extensions/00000000-0000-0000-0000-000000000000 and verify that you see the tunnel error message with the correct link to the extension
2. Navigate …
=> Handle HTML requests for individual extensions

README.md
There's a typo on the README instructions where the `make serve` command breaks with an unclear runtime error. This PR fixes the README instructions.
Follow the instructions on the README to setup the project and you should not see any errors.
=> Fix serve command instructions on readme

packages/ui-extensions-server-kit/src/components/CheckBox/Checkbox.tsx, packages/ui-extensions-server-kit/src/components/Icon/Icon.tsx
issue: #184 
Here are the descriptions for Icon and Checkbox:
=> Adding base description to Icon and Checkbox

api/api.go, api/api_test.go, core/core.go
Related to https://github.com/Shopify/shopify-cli-extensions/issues/10
Move timestamp prop to `lastUpdated` so that the asset url remain unchanged as expected. Consumers that needs to check the last updated time can still access to it through `lastUpdated` in order to handle reloading the extension
=> Move timestamp to a separate prop instead of appending it to the asset url

build/build.go, packages/shopify-cli-extensions/src/configs.ts
This PR changes how we obtain the extension configuration on the JavaScript side. Instead of reading it from disk, the Go server is now expected to supply it via STDIN.
Fixes #212
=> Pass Extension Config from Go to JS via STDIN

packages/ui-extensions-server-kit/scripts/createEntryFiles.ts
We should be using the fully qualified file extension when importing inside esm modules. 
This is currently blocking our webpack 5 builds: https://buildkite.com/shopify/web-staging-builder/builds/2906#8c0950aa-32a7-4aed-8acf-3272e3ce13f2/173-177
🙇
=> Fix mjs file path resolution

Makefile, create/create_test.go, create/templates/extension.config.yml.tpl, support/merge_config.rb
[Issue #210](https://github.com/Shopify/shopify-cli-extensions/issues/210) - Remove entrypoint configuration requirement
* Remove 'development.entries' from extension config template
* Adjust integration test to provide defaults
* Refactor defaults into support/merge_config.rb
=> Default dev entry main

api/api_test.go, api/root/templates/checkout_post_purchase/index.html.tpl, create/templates/checkout_post_purchase/next-steps.txt
Resolution of issue #234 - Next Step Template for Post Purchase
```
Post Purchase Test Extension (Build succeeded)
🔭 > If this is the first time you're testing a Post Purchase extension,
🔭 > please install the Chrome or Firefox browser extension from
🔭 > https://github.com/Shopify/post-purchase-devtools/releases.
🔭 > Once installed, simply enter your extension URL
🔭 > https://example.ngrok.io/extensions/00000000-0000-0000-0000-000000000002.
```
=> Next Step Template for Post Purchase

core/fsutils/fsutils.go, create/create.go, create/create_test.go, create/templates/package.json.tpl, testdata/extension.config.integration.yml, testdata/extension.config.yml
The renderer version is now configured via the extension configuration:
```
extensions[].Development.Renderer.Version
```
instead of being hardcoded to latest. The corresponding [PR in `Shopify/shopify-cli`](https://github.com/Shopify/shopify-cli/pull/2117) will ensure that a version is always passed down.
=> Renderer version

README.md, dev.yml
What do you think about supporting `dev up`?
I hit an error in `make bootstrap` which was actually a problem running `yarn install` inside `tmp/checkout_ui_extension`:
`dev up` fixes it automatically, probably via `shadowenv`:
I added an explanation to the readme of why this is needed but I'm not totally sure it's accurate 😅
=> Avoid yarn errors for Shopify employees by supporting dev up

api/api_test.go, api/root/templates/checkout_post_purchase/index.html.tpl, create/templates/checkout_post_purchase/next-steps.txt
Use anchor tags in index.html.tpl to make post purchase links functional.
=> Make post purchase extension links functional

api/api.go, api/api_test.go, api/root/root.go
Changes:
* Sets `Cache-Control` header to `no-cache` for all static assets served by our fileserver
* Changes the permanent redirects to temporary ones to disable browser caching
Both changes seek to address weird browser caching behaviour that @vividviolet and I observed during testing.
=> Cache-Control: no-cache & Temporary Redirects

dev.yml
Python 2.7 was removed with OS X 12.3 which can break the installation of node packages with native extensions as node-gyp relies on python being present.
This PR makes Python an official dependency to ensure that yarn install functions as expected.
To test this PR run
```sh
$ make clobber
$ dev up
```
If it exits cleanly and a node_modules folder has been produced, all is good.
=> Make Python a project dependency

README.md
Add instructions on how to test the integration with the Shopify CLI using a development build.
=> Readme - testing with a development build

create/templates/projects/beacon_extension/extension.config.yml, create/templates/projects/beacon_extension/src/index.js, testdata/extension.config.yml
ISSUE: https://github.com/Shopify/ce-customer-behaviour/issues/983
CLI:
https://github.com/Shopify/shopify-cli/pull/2075
Adds the beacon extension to the cli-extensions. This will be the only wait to create a new project.
=> initial analytics extension setup

api/api_test.go, core/core.go, core/core_test.go, testdata/extension.config.yml
resolves internal Shopify issue.
Removes `CanAccessNetwork` bool in favor a `Capabilities` list. This change works with https://github.com/Shopify/shopify-cli/pull/2262
`make bootstrap`
`make run serve testdata/extension.config.yml`
| Command | Config yml | Expected json |
| - | - | - |
| `curl http://localhost:8000/extensions/00000000-0000-0000-0000-000000000001` | no capabilities added | `networkAccess: false` |
| `curl http://localhost:8000/extensions/00000000-0000-0000-0000-000000000003` | `network_access: false` | `networkAccess: false` |
| `curl http://localhost:8000/extensions/00000000-0000-0000-0000-000000000002` | `network_access: true` | `networkAccess: true` |
=> adding capabilities list in lieu of canAccessNetwork flag

api/api.go, api/api_test.go, build/build.go, build/build_test.go, core/core.go, go.mod, go.sum, main.go
Closes https://github.com/Shopify/checkout-web/issues/9581.
Necessary for https://github.com/Shopify/checkout-web/issues/9365.
This is a clean slate branch for [this older draft pull request](https://github.com/Shopify/shopify-cli-extensions/pull/260)
This is a follow-up [PR](https://github.com/Shopify/shopify-cli-extensions/pull/237) which will move where `extension.Localization` is being processed from happening at runtime for `HTTP GET /extensions/`, to a new watcher: `build.WatchLocalization`.
The goal of this PR is to increase performance by moving the processing of locales (which requires fs i/o) to the offline build watcher which will only re-process localization if the locale files have changed.
The `localization` property for an extension in the `HTTP GET /extensions/` response …
=> Add localization file watcher

create/templates/projects/checkout_ui_extension/extension.config.yml.tpl
Ensure that extensions of type `checkout_ui_extension` have a name.
=> Add name to checkout_ui_extension config

api/api_test.go, build/build.go, build/script.go, build/script_test.go, core/core.go
I'm extending the configuration object that we pass through standard input to allow passing the path to the Node executable. When present, the logic defaults to it over running the executable through Yarn or NPM.
=> Pass the node executable through the configuration object

Gemfile, Makefile, testdata/test/contract_test.rb
Add basic Ruby tests to validate output from `make integration-tests` (Supercedes https://github.com/Shopify/shopify-cli-extensions/pull/289)
=> Ruby basic contract tests

Makefile, api/api.go, api/api_test.go
This PR fixes 3 issues with the websockets:
- Fix issue where websocket messages were being sent to a closed channel
- Fix error where websocket messages were sent concurrently 
- Suppress writing to a broken pipe error. Once we encounter this error we can safely stop attempting to send notifications as the client has already closed the connection.
Fixes https://github.com/Shopify/shopify-cli-extensions/issues/295 as a result of resolve the above issues.
1. Follow the instructions here to test with a local version of the CLI + the Go binary: https://github.com/Shopify/shopify-cli-extensions#testing-the-integration-with-the-shopify-cli. Ensure you follow the step to set up the `symlink` to the Go binary.
1. Create a Checkout UI Extension
2. Run `shopify extension serve`
3. Click on the …
=> Fix issues with websocket messages

core/core.go, packages/dev-console-app/package.json, packages/dev-console-app/src/App.tsx, packages/dev-console-app/src/DevConsole.module.scss, packages/dev-console-app/src/DevConsole.tsx, packages/dev-console-app/src/translations/en.json, packages/shopify-cli-extensions-test-utils/package.json, packages/shopify-cli-extensions/package.json, packages/ui-extensions-server-kit/package.json, packages/ui-extensions-server-kit/src/ExtensionServerClient/APIClient.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/index.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/types.ts, packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.tsx, packages/ui-extensions-server-kit/src/types.ts, packages/ui-extensions-server-kit/src/utilities/index.ts, packages/ui-extensions-server-kit/src/utilities/isValidSurface.ts, testdata/extension.config.yml, yarn.lock
Related to https://github.com/Shopify/shopify-cli-extensions/issues/306
Allow passing the selected surface to the Dev Console as a search param
- Filter extension selected surface for all events coming from the Dev Server
Manually set the surface for CLI 3.0 extensions to prevent them from being set to "admin" by default
1. Pull this branch and run `make clobber; make bootstrap`
2. Run `make run serve testdata/extension.config.yml`
3. Open http://localhost:8000?surface=admin
4. Verify that you only see Product Subscription extensions
=> Allow passing the selected surface to the Dev Console as a search param

build/build.go, build/script.go, build/script_test.go, packages/shopify-cli-extensions/src/build.ts
When executing `serve` we found a couple of bugs:
- The GO Binary wasn't looking for the entry point at the correct path.
- We've modified the path to include `extension.development.RootDir` as the working directory
- When failing to build, there was no feedback, the process just finishes.
- We've added a `console.error` in case the build fails. That way the go part will receive and report the error.
=> Fix Serve path & build bugs

api/api.go, api/api_test.go
We need to use the go binary behind a reverse proxy so we can serve both the web app and the extensions at the same time under the same ngrok tunnel.
That means that the websocket is also behind a localhost proxy, this was causing the go binary to think that the remote host is `localhost` (because all connections were received from the localhost proxy).
Instead of using the `connection.rootUrl` to build the extensions URLs, we use the `publicUrl` set in the config yml file. This way we force the go server to use the tunnel URL ignoring the proxy host.
Looking forward for any feedback on this solution or if you think there could be a better approach :)
=> Use publicUrl instead of the request host when building websocket messages

core/core.go, create/templates/projects/pos_ui_extension/.shopify-cli.yml.tpl, create/templates/projects/pos_ui_extension/package.json.tpl, create/templates/projects/pos_ui_extension/src/index.tpl, create/templates/shared/pos_ui_extension/javascript.js, create/templates/shared/pos_ui_extension/next-steps.txt, create/templates/shared/pos_ui_extension/react.js, packages/dev-console-app/src/ActionSet/ActionSet.test.tsx, packages/dev-console-app/src/ActionSet/ActionSet.tsx, packages/dev-console-app/src/QRCodeModal/QRCodeModal.test.tsx, packages/dev-console-app/src/QRCodeModal/QRCodeModal.tsx, packages/ui-extensions-server-kit/src/ExtensionServerClient/types.ts, packages/ui-extensions-server-kit/src/utilities/isValidSurface.ts, testdata/extension.config.yml
Adding POS UI Extension into Shopify CLI Extensions Template. Our goal is to `create`, `build`, and `serve` this new extension through Shopify CLI.
closes https://github.com/Shopify/shopify-cli-extensions/issues/272
1. Am I missing any tests or other configurations?
2. Any suggestions for the `react` or `javascript` file?
Once the PR is approved, we only need to create tag and release it as described here: https://github.com/Shopify/shopify-cli-extensions#publishing-the-go-binary
=> Adding POS UI Extensions into Shopify CLI Extensions

packages/dev-console-app/src/ExtensionRow/ExtensionRow.tsx
Split row selection and checkbox selection handler logic so that both are not triggered concurrently when the checkbox is toggled.
=> Fix Checkbox double-toggle on Dev Console

api/api_test.go, core/core.go, core/core_test.go, packages/dev-console-app/src/App.tsx
Fixes https://github.com/Shopify/shopify-cli-extensions/issues/203
There is a quirk in Go where a boolean that has not been initialized is equivalent to `false`. When an extension update
event comes in with partial data as all boolean values that have not been initialized is defaulted to `false`. This cause a strange bug where `true` boolean values are overwritten by non-initialized boolean as `false`.
This is fixed by using a pointer to a boolean to distinguish between a boolean that has been set to `false` vs. one that has not been set.
**Before**
https://user-images.githubusercontent.com/29458473/173366406-ffd9bbdf-d25e-4e17-a498-1578cec0c12a.mov
**After**
https://user-images.githubusercontent.com/29458473/173366466-2a0c439d-c9e9-42ce-8ef9-62c2eae4289d.mov
1. Modify …
=> Fix issue where partial extension updates was forcing boolean values to be false

packages/shopify-cli-extensions/src/build.ts
We need to ensure legal comments are preserved in order to not break licensing agreements when using open source libraries. Previously we were linking to a separate license text file but this is not easily accessible when the extension is uploaded to the CDN. Therefore the best solution is to preserve the license comments in the source code.
=> Exclude all legal comments when building extensions

build/build.go, create/templates/shared/checkout_post_purchase/next-steps.txt, create/templates/shared/checkout_ui_extension/next-steps.txt, create/templates/shared/pos_ui_extension/next-steps.txt, create/templates/shared/product_subscription/next-steps.txt
We want to control how extensions URLs are presented to the users from the CLI. In order to provide a consistent output with the rest of the CLI as well as having more flexibility to provide detailed instructions without being lost in the logs (since we serve frontend, backend and extensions at the same time, it gets messy)
This PR removes all `next-step` templates and that info will be handled by CLI now.
=> Remove next-step templates

create/templates/shared/checkout_ui_extension/javascript.js, create/templates/shared/checkout_ui_extension/react.js
This PR makes the default Checkout UI extension more visually noticeable inside the Checkout UI. The previous layout was too easy to miss and led to confusion if the extension was showing up or not.
Fixes https://github.com/Shopify/ui-extensions/issues/326
Before:
After:
=> Make default extension more visually noticeable

api/api_test.go, core/core.go
Given that there has been no breaking changes to the API, we do not need to bump the API version. We need to set this back to "3" to avoid issues on Mobile thinking it cannot read the manifest provided by the API even though it is compatible
=> Set API version back to 3 as there has been no breaking changes

api/api.go
See https://github.com/Shopify/checkout-web/issues/11653
Allow an ngrok header to dismiss their intersitial which was preventing extensions from loading extensions from loading.
🎩 instructions
Create the equivalent of [`yarn dev` to preview an extension](https://shopify-dev-staging2.shopifycloud.com/apps/checkout/custom-fields/getting-started#step-2-preview-your-extension) using this version of `shopify-cli-extensions`.
Start this spin instance:
```bash
spin up -n ngrok-fix - << 'END'
---             
schema: v1
extend: checkout-ui-extension-dev
repos:
- checkout-web:
branch: kumar-ngrok-workaround
END
```
* From `spin open`, click to open a new checkout
* Use `?dev=<extension-server>` to install an extension
=> Fix extensions by allowing checkout to send an ngrok header

build/localization.go
resolves https://github.com/Shopify/checkout-web/issues/11552
when a `locales` folder is not present no translations will be present in the extension causing errors within checkout-web. This is required and expected.
* have a working extension
* delete your `extensions/my_extension_name/locales` directory
* build the go binary and copy to where CLI3 references it internally: `$ go build && cp ./shopify-cli-extensions /Users/${your_name_here}/Library/Caches/shopify-cli-nodejs/vendor/binaries/extensions//v0.20.2-darwin-arm64`
* `yarn dev`
* server should log an error to stderr
=> log an error without locales directory

dev.yml, shopify-extensions-debug
Follow-up to [this PR](https://github.com/Shopify/shopify-cli-extensions/pull/368), adding suggestions to add `delve` to Homebrew dependencies.
=> Add delve as Homebrew dependency

build/localization.go
Reverts Shopify/shopify-cli-extensions#364
This introduces an error for extensions not currently using locales:
We need to find a different approach.
=> Revert "log an error without locales directory"

dev.yml, packages/dev-console-app/package.json, yarn.lock
Turns out we don't need node-sass.
Also updated the dev.yml dependencies to match those in the CLI repo, checked that everything still works, making it easier for the merge.
Fixes https://github.com/Shopify/shopify-cli-planning/issues/338
=> Remove node-sass dependency as it is not used
